services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5075:5075"

  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-gradio
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://api:5075
    depends_on:
      - api